### PR TITLE
Create ETS table with country and city name

### PR DESCRIPTION
**Pull request by vinibrsl**
See this PR for context: https://github.com/plausible/analytics/pull/2608

### CODE REVIEW

**Comment by vinibrsl** [comment]
> 👋 @vinibrsl
> 
> Would duplicate {name, country} keys be a problem? For example, there can be multiple cities in a country with the same name, like [Springfield.](https://en.wikipedia.org/wiki/Springfield) If the ets table type is set, I guess only the last one inserted would be used for the lookups.
> 
> https://github.com/plausible/location/pull/2#discussion_r1100124960

Good catch, @ruslandoga! I can't think of any easy way to address the issue with the data we get from Google Analytics - city name and country code only. As the country matches, cities will be displayed correctly with the country flag on the dashboard. Filtering by city would be a problem but we don't allow filtering when displaying Google Analytics data.

In my opinion we can leave as-is if we don't find a solution. I added doctags to the function to make clear this issue with cities that have the same name. And also a test to make sure it works.

**Comment by ruslandoga** [comment]
I think we can get slightly more accurate results if we prepare the mapping of [geoid](https://developers.google.com/analytics/devguides/collection/protocol/v1/geoid) into geoname id by using all available info.

**Comment by ruslandoga** [comment]
I looked at the fixtures and it doesn't seem like google responses include geoid. Is that right?

**Comment by ruslandoga** [comment]
Can we request a geoid here: https://github.com/plausible/analytics/blob/d71326b730607cc84e2374616a14f4960a967fa7/lib/plausible/google/report_request.ex#L60 ?

**Comment by vinibrsl** [comment]
We can add the `ga:cityId` property in the GA report request to include the Geo ID. However, I've given some thought to the effort required to map to GeoNames, plus maintaining this list, and I don't think it's worth it. This is because GA imports, at least Universal Analytics imports, is a feature that we don't plan to support in the long run. Additionally, importing GA cities wasn't a feature request, and I decided to add this feature while I was fixing a GA bug a customer reported.

Considering that this is indeed an edge case, I wanted to get your thoughts on whether we should still fix it :)

**Pull request merged**
